repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
  - repo: local
    hooks:
      - id: format
        name: Format
        entry: just fmt
        pass_filenames: false
        types: [go]
        language: system
      - id: lint
        name: Lint
        entry: just lint
        pass_filenames: false
        language: system
      - id: test
        name: Test
        entry: just test
        pass_filenames: false
        language: system
